language: objective-c
osx_image: xcode7.2
xcode_workspace: ClubeJohnnie/ClubeJohnnie.xcworkspace
xcode_scheme: ClubeJohnnieTests
script:
  xctool
  -workspace ClubeJohnnie/ClubeJohnnie.xcworkspace
  -scheme ClubeJohnnieTests
  build
  test
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO
