language: objective-c
osx_image: xcode7.3
xcode_workspace: ClubeJohnnie/ClubeJohnnie.xcworkspace
xcode_scheme: ClubeJohnnieTests
script: xctool -workspace cam-pro.xcworkspace -scheme cam-beta clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
